### ISSUE TITLE
how to connect phoenix with user and password?

### ISSUE THREAD

**Issue by ivanjoy42** [Boostport/avatica#28]
like following java code:
DriverManager.getConnection("jdbc:phoenix:thin:url=http://192.168.1.1:8765;serialization=PROTOBUF", "user", "password");

**Comment by F21** [comment]
@ivanjoy42 
Thanks for opening the issue. 
I have not implemented authentication yet. I think the implementation will be part of the DSN: 

```
http://[username:password[|comma-separated-roles]]@address:port[/schema][?parameter1=value&...parameterN=value]
```

I think it will only be possible to implement HTTP Basic and HTTP digest auth at the moment, as there is no pure-go kerberos client yet.

Would you be able to implement this and open a PR?

**Comment by F21** [comment]
@ivanjoy42 After investigating, I cannot find any information where Phoenix/Hbase supports username/password pairs. The only option is to use kerberos.

Have you tried the code you posted in a Java environment?

```
DriverManager.getConnection("jdbc:phoenix:thin:url=http://192.168.1.1:8765;serialization=PROTOBUF", "user", "password");
```

**Comment by ivanjoy42** [comment]
I connect to phoenix through [Phoenix Query Server](http://phoenix.apache.org/server.html)
I did not use kerberos. Just modify Phoenix Query Server server side java code to verify user and password.

For java use Phoenix Query Server client, phoenix-version-thin-client.jar
DriverManager.getConnection("jdbc:phoenix:thin:url=http://192.168.1.1:8765;serialization=PROTOBUF", "user", "password");

For python use [phoenixdb](https://bitbucket.org/lalinsky/python-phoenixdb)
phoenixdb.connect('http://192.168.1.1:8765', user='user', password='password')

For go I can also connect to Phoenix Query Server.
But how to add user/password param?

**Comment by F21** [comment]
@ivanjoy42, the Go driver currently does not support support using a username and password pair yet.

I am using the pre-built phoenix query server by running: `bin/queryserver.py start &`.

I tried grepping the python phoenixdb project, but cannot see how it is using the username and password.

Can you show the code modifications to the Phoenix Query Server?

**Comment by F21** [comment]
hey @ivanjoy42,

After some research, here are the possible authentication methods:

- Pass username and password directly through to the backend database (like your example).
- Pass username and password to avatica (authentication is for avatica only) using either HTTP Basic or Digest auth.
- Use SPNEGO/Kerberos

I think the easiest to implement would be your use-case:
```
http://username:password@your-phoenix-queryserver:1234/schema
```

For Keberos (in the future when there is a good pure-go kerberos library, or maybe using cgo):
```
http://your-phoenix-queryserver:123456/schema?keytab=path/to/keytab&principal=someprincial
```

For Avatica auth, it is more complicated. We need to account for the possibility where the driver authenticates with avatica, then passes a separate username/password down to the database. Maybe something like this:

```
http://username:password@your-phoenix-queryserver:1234/schema?avatica_user=avatica&avatica_password=avatica-password&authentication=DIGEST
```

Let me know what your thoughts are.

**Comment by ivanjoy42** [comment]
Thanks for your replay!

I've been tried above DSN methods, but failed.

I modify phoenix queryserver by this way: open following file, add 3 lines between 431-432 line, like this:

phoenix-core-4.10.0-HBase-1.1-sources/org/apache/phoenix/query/ConnectionQueryServicesImpl.java
```
    private void openConnection() throws SQLException {
        try {
            boolean transactionsEnabled = props.getBoolean(
                    QueryServices.TRANSACTIONS_ENABLED,
                    QueryServicesOptions.DEFAULT_TRANSACTIONS_ENABLED);

            String user = props.get("user");
            String password = props.get("password");
            logger.info("Test user: " + user + "password: " + password);

            this.connection = HBaseFactoryProvider.getHConnectionFactory().createConnection(this.config);
            GLOBAL_HCONNECTIONS_COUNTER.increment();
```

**Comment by F21** [comment]
@ivanjoy42 73eeb51cf5aab4c0a10454c5365b10dd5653fc97 supports passing the JDBC username and password to the backing database. Please give it a go and let me know how it works for you.
