### ISSUE TITLE
Can it work for phoenix at version 4.6.x?

### ISSUE THREAD

**Issue by Cheers0606** [Boostport/avatica#42]
Can it work for phoenix at version 4.6.x?
I have tried at phoenix 4.6.0 and it throws the error: EOF

**Comment by F21** [comment]
Hi @Cheers0606 

The first version of the driver is developed against Phoenix 4.8.0, therefore it is untested against 4.6.0. There were lots of changes to calcite/avatica at that stage, so I suspect phoenix 4.6.0 would not work.

See the compatibility table here: https://github.com/Boostport/avatica#version-compatibility

**Comment by Cheers0606** [comment]
Thanks a lot.

**Comment by Cheers0606** [comment]
@F21 👍  Thanks a lot.
