### ISSUE TITLE
gopkg.in/jcmturner/gokrb5.v1 dependency once again broken

### ISSUE THREAD

**Issue by kenshaw** [Boostport/avatica#44]
For some reason, the maintainer of the `gokrb5.v1/*` packages has made breaking API changes again, just in the last 48 hours. I had thought that the change/move to the gopkg.in URL was a way of signalling API stability, but it appears that is not the case.

I would otherwise fix something like this myself, but do not at the moment have the time to dig through the kerberos package / API and figure out what changes in the `avatica` package are required. Opening an issue here in the hopes this can get fixed sometime soon, as I'm moving forward with a new `usql` release, and would ideally prefer to have it "go get"-able as well as using packaged dependencies.

**Comment by F21** [comment]
Tagged as `v2.2.1`.

**Comment by kenshaw** [comment]
Thanks! Really appreciate the expediency!
