### ISSUE TITLE
try to upsert []byte value got error

### ISSUE THREAD

**Issue by bigjjboom** [Boostport/avatica#50]
when try to use db.Exec() to insert one row which value like [0 0 0 1], got an error "InvalidProtocolBufferException: Protocol message had invalid UTF-8.". 
So how to store []byte?

**Comment by F21** [comment]
Can you show the code you are using?

There are a few tests storing `[]byte`s here: 

- https://github.com/Boostport/avatica/blob/master/driver_test.go#L196
- https://github.com/Boostport/avatica/blob/master/driver_test.go#L497

**Comment by bigjjboom** [comment]
oh, I have used in wrong way, just convert []byte to string and construct the sql string, thanks a lot!

**Comment by F21** [comment]
Glad you got it working! I'll close this issue.
