### ISSUE TITLE
Error during "go get"

### ISSUE THREAD

**Issue by ernierasta** [Boostport/avatica#52]
Hi, just simple to fix error. Prevents building.

```bash
$ go get -u github.com/Boostport/avatica
# github.com/Boostport/avatica
./driver.go:55:28: multiple-value uuid.NewV4() in single-value context
```
uuid.NewV4() returns also error.

**Comment by F21** [comment]
I've opened #53 to fix this. The `go.uuid` package is pinned to master on the commit 36e9d2ebbde5e3f13ab2e2. However, I would still recommend using `dep` to install the library, in case a breaking change is pushed to master again.
